// ==========================================
// DirectFontBytesTable
//
// In a file of its own, and named after the class,
// because Unity insists: a ScriptableObject's MonoScript
// is found by file name, and an asset whose type cannot
// be found is loaded with no script attached at all.
//
// It was declared inside DirectFontBytes.cs in 2.1.7,
// which produced
//
//   "No script asset for DirectFontBytesTable"
//   "Script attached to 'DirectTMPFontBytes' ... is
//    missing or no valid script is attached"
//
// and a baked table that always loaded as null - so the
// font bytes were carried into the build and then could
// not be read back out of it.
// ==========================================
using UnityEngine;

namespace UnityDirectTMP
{
    /// <summary>
    /// Font files baked for a player build: one row per <see cref="Font"/>
    /// that a <see cref="DirectFont"/> somewhere points at.
    /// <para>
    /// Built by <c>Unity DirectTMP ▸ Bake Fonts For Build</c> and refreshed
    /// automatically before every build. It can also be edited by hand — a
    /// font listed here is available to the joiner on device whether anything
    /// found it automatically or not.
    /// </para>
    /// </summary>
    public sealed class DirectFontBytesTable : ScriptableObject
    {
        /// <summary>One font and the file it was imported from.</summary>
        [System.Serializable]
        public struct Row
        {
            [Tooltip("The imported font a Direct Font component points at.")]
            public Font font;

            [Tooltip("That font's file, copied to a .bytes asset so a build can read it.")]
            public TextAsset bytes;
        }

        [Tooltip("Regenerated by the baker. Rows added by hand are kept.")]
        [SerializeField] private Row[] rows = new Row[0];

        /// <summary>Every baked font. Never null.</summary>
        public Row[] Rows
        {
            get => rows ?? (rows = new Row[0]);
            set => rows = value ?? new Row[0];
        }

        /// <summary>
        /// The file behind <paramref name="font"/>, or null when it was not
        /// baked. Matched by reference first — the build shares one instance
        /// per asset — and by name only as a safety net.
        /// </summary>
        public byte[] For(Font font)
        {
            if (font == null) { return null; }

            Row[] all = Rows;

            for (int i = 0; i < all.Length; i++)
            {
                if (all[i].font == font && all[i].bytes != null) { return all[i].bytes.bytes; }
            }

            for (int i = 0; i < all.Length; i++)
            {
                if (all[i].bytes == null || all[i].font == null) { continue; }
                if (all[i].font.name == font.name) { return all[i].bytes.bytes; }
            }

            return null;
        }
    }
}
